export const TextConstant = {
  Dashboard: "Dashboard",
  ToDo: "ToDo",
  Weather: "Weather",
  todolist: "To Do List",
  completed: "Completed",
  addTask: "Add Task",
  clearAll: "Clear All",
  clearCompleted: "Clear Completed",
  userProfile: "User Profile",
  name: "Name: ",
  email: "Email: ",
  linkedin: "Linkedin: ",
  weather: "Weather",
  weatherError: "Unable to fetch Data",
  forecastDay: "1 day-Forecast",
  high: "High: ",
  low: "Low: ",
  currentDT: "Current Date and Time: ",
  sunrise: "Sunrise: ",
  sunset: "Sunset: ",
  wind: "Wind: ",
  temp: "Temp: ",
  feels: "Feels like: ",
};
